{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinelstream.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinelstream.labels" . | nindent 4 }}
    {{- include "sentinelstream.selectorLabels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.stringData | nindent 2 }}
{{- end }}
