{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- $serviceAccount := default $root.Values.serviceDefaults.serviceAccount $svc.serviceAccount }}
{{- if $serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelstream.serviceAccountName" (dict "root" $root "name" $name "service" $svc) }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "sentinelstream.labels" $root | nindent 4 }}
    {{- include "sentinelstream.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- include "sentinelstream.renderStringMap" . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
