apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinelstream
  namespace: sentinelstream
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: sentinelstream.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analyst-console
                port:
                  number: 8007

